
project_id = "uwiikfumbokbxgydyscs"

[api]
enabled = true
schemas = ["public", "storage", "graphql_public"]

[db]
major_version = 15

[studio]
enabled = true
api_url = "http://localhost"

[inbucket]
enabled = true

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = true

[functions.fetch-mcp-servers]
verify_jwt = false
