// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwiikfumbokbxgydyscs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3aWlrZnVtYm9rYnhneWR5c2NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNjM2MTgsImV4cCI6MjA1NjgzOTYxOH0.4NiwjG5fyG2d6kZy_2ZepwJ0SAHFqJD5gGMZ8KKLD34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);